sudo: required
dist: trusty
language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtest-dev cmake
  - cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib/
install:
  - make get-check-deps
script: make check
compiler:
  - clang
  - gcc

