sudo: required
dist: trusty
language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtest-dev cmake
  - pushd /usr/src/gtest
  - sudo cmake CMakeLists.txt -DCMAKE_CXX_COMPILER=`which $CXX`
  - sudo make
  - sudo cp *.a /usr/lib/
  - popd
install:
  - make get-check-deps
script: make check
compiler:
  - clang
  - gcc

